language: python
sudo: false
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install flake8 codecov

install:
  - pip install .

script:
  - flake8 --ignore=E501 --exclude=__init__.py .
  - pushd /tmp && python -c 'import pypinksign' && popd
  - coverage run -m pypinksign.test_pinkSign

after_success:
  - codecov # submit coverage
